[project]
name = "campushub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argon2-cffi>=25.1.0",
    "psycopg[binary]>=3.3.2",
    "pyqt6>=6.10.1",
]
